### ISSUE TITLE
Predicates link in the sidebar leads to wrong Predicates section

### ISSUE THREAD

**Issue by oeb25** [viperproject/tutorial#13]
The [Predicates](https://viper.ethz.ch/tutorial/#predicates) link on the [Viper Tutorial](https://viper.ethz.ch/tutorial/) currently links to the first occurrence of a predicates section, which is the subsection under [Top-level declarations](https://viper.ethz.ch/tutorial/#top-level-declarations), instead of the top-level section by the same name.

I see this is not a problem with [Functions](https://viper.ethz.ch/tutorial/#functions-1), as that link is suffixed with at `-1`, so maybe something similar could be done here.

It is a small problem, but might nevertheless confuse some newcomers!

**Comment by gauravpartha** [comment]
Fixed byhttps://github.com/viperproject/tutorial/pull/12.
